### ISSUE TITLE
Compatibility with different Python versions

### ISSUE THREAD

**Issue by annayqho** [annayqho/TheCannon#14]
I just learned how to set up virtual environments to test my code in. But I'm not sure which virtual environments to make sure my code is compatible with. I have Python 2.7.6; I could perhaps ensure that it's compatible with 2.7.5 (which HW has) but beyond that I'm not sure how many (and which) versions would be appropriate to test. @davidwhogg , your feedback here would be very helpful!

**Comment by davidwhogg** [comment]
I can't imagine any possible reason that if you are compatible with 2.7.6 you wouldn't be compatible with 2.7.5.  If there *is* any such thing, I would love to see the error message!

**Comment by annayqho** [comment]
Oh, I see. Then I think it's a compatibility issue between different versions of Scipy rather than different versions of Python. So then the testing to be done is between different Scipy (and probably Numpy, too) packages...

**Comment by HWRix** [comment]
I see two options:
-- state what the version requirements are; and ask the user to get with it (I would suspect it 
   is mostly scipy and numpy)
-- or write it that its works with an earlier version of scipy & numpy, as I presume there is far more forward compatibility
