### ISSUE TITLE
What is "Cannonisable"? Write an introduction explaining the input data requirements.

### ISSUE THREAD

**Issue by annayqho** [annayqho/TheCannon#31]
- radial velocity shifted
- common wavelength grid

**Comment by davidwhogg** [comment]
- need inverse variance estimates, one per pixel
- common line-spread function

**Comment by davidwhogg** [comment]
* consistent continuum normalization based on fitting or means, but not medians or quantiles!

**Comment by annayqho** [comment]
just to make sure I understand that last point: incoming spectra should *not* be continuum-normalized with medians or quantiles, because we are subsequently going to continuum-normalize with medians?

**Comment by davidwhogg** [comment]
No, we will *NEVER* normalize with medians -- in the Cannon we only used the quantiles as a starting point, and then we iterated to get a list of wavelengths that are "continuum safe" and then we fit a curve through those points.  If the input data have had anything done to them that involves medians or quantiles, it will break the model -- or distort it as a function of SNR.

**Comment by annayqho** [comment]
ok, this information lives in section 2.2 of the current draft of the paper.
