### ISSUE TITLE
repo needs license and citation instructions

### ISSUE THREAD

**Issue by davidwhogg** [annayqho/TheCannon#35]
Add the MIT license (see my HoneyComb repo for an example of how that looks).

Edit the README to say so.

Add below that a requirement to cite Ness et al and Ho et al (in prep).

Get me to sign off on all this before closing issue.

**Comment by annayqho** [comment]
@davidwhogg , added. Let me know if it looks okay.

**Comment by davidwhogg** [comment]
signing off
