### ISSUE TITLE
LAMOST Continuum Normalization

### ISSUE THREAD

**Issue by annayqho** [annayqho/TheCannon#39]
# Experiment:
- Pseudo-continuum normalize
- Identify continuum pixels using pseudo-continuum normalized spectra
- Apply continuum normalization to the original spectra, not the pseudo-continuum normalized spectra

Note from Melissa: In the tests I did the pixels did not converge, I am not sure if I was doing something wrong but if you find the same thing let me know  - the tests I did were to determine the new pixels that are continuum from the spectrum just normalised using the pixels for the preceding found pixels and polynomial/trig fit. I found that a wave got built in and so when I divided it the spectra looked modulated by a sine wave.

**Comment by davidwhogg** [comment]
rinse and repeat -- the system should converge if repeated.  Or if it doesn't, let's look at why.

**Comment by annayqho** [comment]
Maybe continuum normalization isn't the right goal: the goal should be consistent normalization that preserves our assumptions, not the identification of the true continuum.
