### ISSUE TITLE
LAMOST 

### ISSUE THREAD

**Issue by annayqho** [annayqho/TheCannon#40]
- Train on highest-SNR LAMOST spectra with APOGEE labels (the usual 3 + alpha enh.)
- Test on the full 12,000 LAMOST set and compare to APOGEE labels
- Take-one-out tests

**Comment by mkness** [comment]
- first point - I would start with just first 3 labels and get that working with no bias at low SNR then move to 4 labels 
- second point: apply test step to the stars = (full set of 11000 stars) - (stars in training set).
