### ISSUE TITLE
Label estimate uncertainties

### ISSUE THREAD

**Issue by tingyuansen** [annayqho/TheCannon#43]
The code formally derives uncertainties for the label estimates. If I understand correctly, the calculation does not include the coefficient uncertainties. Only the flux uncertainties are included. I am guessing the uncertainty of these "transferred-labels" might be too optimistic.

**Comment by davidwhogg** [comment]
To use these (to first order), we need to compute, at the best-fit label position, the full derivative d(label) / d(coefficient) and then multiply them around the covariance matrix.  Or something like that...

**Comment by tingyuansen** [comment]
I agree. But I think it should be something like d(label)/d(coefficient,flux), since flux also contains uncertainties in this case. We can probably also assume cov(coefficient,flux) = 0. The question is however whether we can estimate cov(coefficient) in the first place -- the topic in another post. We should continue our fight there :) .

**Comment by davidwhogg** [comment]
Yes, we already have cov(coefficient).

**Comment by tingyuansen** [comment]
I would argue that we might not have that (see the other post on coefficient uncertainties).
