### ISSUE TITLE
Purge training set of objects w/ sketchy APOGEE labels

### ISSUE THREAD

**Issue by annayqho** [annayqho/TheCannon#51]
From the Holtzman et al. paper:
-- Warning on Teff for giants outside the range of those used to derive the calibration (3500 < Teff < 6000)
-- COLORTE_BAD means that the deviation between the ASPCAP temperature and the col-temp relation from another paper is > 1000K
-- STAR_BAD: "stars with this bit should not be used for parameter/abundance analysis"
-- In the allStar file, "TEFF, LOGG, PARAM_M_H, PARAM_ALPHA_M" are the recommended values for these quantities
-- STAR_BAD bit: "stars with unreliable parameters." STAR_WARN uses less stringent criteria.
-- "ASPCAP results at cooler temperatures Teff < 4000 K may be more uncertain"
-- Before using an alpha-enhancement value, confirm that it's not near a grid edge, which would be indicated by the ELEMENTFLAG bitmask in which GRIDEDGE_BAD or GRIDEDGE_WARN is set
-- Below Teff < 3800, CALRANGE_WARN is set in the ELEMFLAG bitmask because the calibration is uncertain
-- In STARFLAG, the persistence bit indicates uncertain abundances
-- Abundance measurements are less certain at cool (Teff<4000) warm stars and logg < 0
-- ALPHAFE_WARN, M_H_WARN, METALS_WARN

**Comment by davidwhogg** [comment]
These comments / cuts should be put into a function that applies them.  The function should be commented so it is fully human-readable, and the comment header should cite out to the Holtzman paper.
