### ISSUE TITLE
weird alpha plume

### ISSUE THREAD

**Issue by annayqho** [annayqho/TheCannon#61]
things to try:
-- train only on the good stars, test on good+bad
-- train on bad, test on bad
-- train on partial regions of the spectrum to see if there are particular regions causing the model to break

**Comment by davidwhogg** [comment]
can you show me a figure?

**Comment by mkness** [comment]
The [Ca/Fe] and [Mg/Fe] versus [alpha/Fe] (APOGEE) relations show a large scatter (partially there is a larger offset at lower SNR but also high SNR are offset) > Are the stars that are up in the offset alpha-plume in LAMOST also the ones that are the furthest from the 1:1 relation in the Ca/Fe v. alpha/Fe results from APOGEE (or Mg/Fe v. alpha/Fe) ? I'm wondering what the effect would be if elements dominating the overall alpha/Fe result from APOGEE are dissimilar to the elements that dominate in LAMOST - i.e a potential issue if the scale between individual alpha elements is offset. Had not considered this. Also, the stars that are in the offset alpha-plume do not correspond to the low SNR Apogee stars do they?

**Comment by davidwhogg** [comment]
I remain concerned that this could be continuum.  I want to see exactly what's being done there.

**Comment by annayqho** [comment]
convergence failure! yay!
