### ISSUE TITLE
thank Yuan-Sen Ting in the current paper

### ISSUE THREAD

**Issue by davidwhogg** [annayqho/TheCannon#67]

**Comment by annayqho** [comment]
done, thank you. is this worth re-uploading to the arXiv, or should I wait until I have a critical mass of updates?

**Comment by mkness** [comment]
I would wait until after the ref. report

**Comment by davidwhogg** [comment]
I agree with @mkness: Unless there is something huge and embarrassing, we should only re-submit to arXiv when we respond to referee.
